// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: odometer

#ifndef _ODOMETER_UI_H
#define _ODOMETER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel01;
extern lv_obj_t * ui_Label01;
extern lv_obj_t * ui_Panel02;
extern lv_obj_t * ui_Label02;
extern lv_obj_t * ui_Panel03;
extern lv_obj_t * ui_Label03;
extern lv_obj_t * ui_Panel04;
extern lv_obj_t * ui_Label04;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
